# Generated by Django 2.1.15 on 2020-05-15 02:01

import articles.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='제목')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='내용')),
                ('to_who', models.TextField(default='', verbose_name='대상')),
                ('detail_plan', models.TextField(default='', verbose_name='상세 일정')),
                ('price', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1000), articles.models.unit_100], verbose_name='가격')),
                ('participations', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='참가 가능 인원')),
                ('event_date', models.DateTimeField(verbose_name='날짜')),
                ('image', models.ImageField(default='', upload_to=articles.models.user_path)),
                ('thumnail_image', models.ImageField(blank=True, upload_to='')),
                ('category', models.CharField(choices=[('스포츠', '스포츠'), ('이색체험', '이색체험'), ('쿠킹', '쿠킹'), ('예술', '예술'), ('관람', '관람'), ('기타', '기타')], default='', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='평점')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WomanParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='man_participations',
            field=models.ManyToManyField(blank=True, related_name='man_participations', through='articles.ManParticipation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='woman_participations',
            field=models.ManyToManyField(blank=True, related_name='woman_participations', through='articles.WomanParticipation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='womanparticipation',
            unique_together={('user', 'article')},
        ),
        migrations.AlterUniqueTogether(
            name='manparticipation',
            unique_together={('user', 'article')},
        ),
    ]
