# Generated by Django 3.0.5 on 2020-04-16 14:20

import articles.models
import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='제목')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('price', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1000), articles.models.unit_100], verbose_name='가격')),
                ('participation', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='참가 가능 인원')),
                ('men_applicant', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='남성 신청인원')),
                ('wemen_applicant', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='여성 신청인원')),
                ('event_date', models.DateTimeField(verbose_name='날짜')),
                ('image', models.ImageField(default='', upload_to=articles.models.user_path)),
                ('thumnail_image', models.ImageField(blank=True, upload_to='')),
                ('category', models.CharField(choices=[('스포츠', '스포츠'), ('이색체험', '이색체험'), ('쿠킹', '쿠킹'), ('예술', '예술'), ('관람', '관람'), ('기타', '기타')], default='', max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
