# Generated by Django 3.0.5 on 2020-04-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='men_applicant',
            new_name='man_applicant',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='wemen_applicant',
            new_name='woman_applicant',
        ),
    ]
