# Generated by Django 2.1.15 on 2020-04-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200419_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detail_plan',
            field=models.TextField(default='', verbose_name='세부일정'),
        ),
        migrations.AddField(
            model_name='article',
            name='to_who',
            field=models.TextField(default='', verbose_name='대상'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시간'),
        ),
    ]
