# Generated by Django 2.1.15 on 2020-04-25 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0006_auto_20200425_1750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='man_participation',
            new_name='ManParticipation',
        ),
        migrations.RenameModel(
            old_name='woman_participation',
            new_name='WomanParticipation',
        ),
    ]
