# Generated by Django 2.1.15 on 2020-04-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200425_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='participation',
            new_name='participations',
        ),
    ]
