# Generated by Django 3.0.5 on 2020-04-04 03:01

import articles.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='제목')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='내용')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성시간')),
                ('price', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1000), articles.models.unit_100], verbose_name='가격')),
                ('participation', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), articles.models.check_even], verbose_name='참여 인원')),
                ('event_date', models.DateTimeField(verbose_name='날짜')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
