# Generated by Django 2.1.15 on 2020-04-06 00:35

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200404_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='내용'),
        ),
    ]
