# Generated by Django 2.1.15 on 2020-05-15 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, unique=True, verbose_name='닉네임')),
                ('profile_photo', models.ImageField(upload_to='')),
                ('birthday', models.DateField(blank=True, default='2020-01-01', verbose_name='생일')),
                ('gender', models.CharField(choices=[('남', '남'), ('여', '여')], max_length=2, verbose_name='성별')),
                ('host_introduce', models.TextField(blank=True, verbose_name='호스트')),
                ('host_career', models.TextField(blank=True, verbose_name='경력사항')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
