# Generated by Django 3.0.5 on 2020-04-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200404_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='host_career',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='host_introduce',
            field=models.TextField(blank=True),
        ),
    ]
