# Generated by Django 2.1.15 on 2020-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200419_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='accounts/static/accounts/img/수민사진.jpg', upload_to=''),
        ),
    ]
