# Generated by Django 2.1.15 on 2020-04-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200423_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='accounts/img/수민사진.jpg', upload_to=''),
        ),
    ]
