# Generated by Django 2.1.15 on 2020-04-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200425_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default='2020-01-01', verbose_name='생일'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('남', '남'), ('여', '여')], max_length=2, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='host_career',
            field=models.TextField(blank=True, verbose_name='경력사항'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='host_introduce',
            field=models.TextField(blank=True, verbose_name='호스트'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=64, unique=True, verbose_name='닉네임'),
        ),
    ]
