# Generated by Django 3.0.5 on 2020-04-23 14:39

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200423_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to=''),
        ),
    ]
